### ISSUE TITLE
Patch has been nulled by Proxmox developers upstream

### ISSUE THREAD

**Issue by samip5** [thenickdude/qemu-debian#1]
Please revisit this, as I really need mips support.

https://lists.proxmox.com/pipermail/pve-devel/2017-October/028912.html

**Comment by thenickdude** [comment]
You can now use my pve-qemu repo's new "alien-architectures" branch to add mips support to Proxmox:

https://github.com/thenickdude/pve-qemu/tree/alien-architectures

It builds and installs to replace Proxmox's native pve-qemu package, but adds support for mips-softmmu, mips64-softmmu, mips64el-softmmu, mipsel-softmmu, ppc-softmmu, ppc64-softmmu, riscv32-softmmu, and riscv64-softmmu.

You can build it on Proxmox (or, better, a Debian 10 container with the Proxmox no-subscription repo added to apt.sources) like so:

```bash
apt-get build-dep qemu
apt install libjemalloc-dev libpci-dev libproxmox-backup-qemu0-dev libsdl1.2-dev libsystemd-dev meson python3-sphinx quilt texi2html check lintian

git clone -b alien-architectures https://github.com/thenickdude/pve-qemu.git
cd pve-qemu
make
```

Install the resulting debs with "dpkg -i *.deb" and it'll add qemu-system-mips etc for you (as well as replacing your regular qemu-system-x86_64 binary).

**Comment by samip5** [comment]
> You can now use my pve-qemu repo's new "alien-architectures" branch to add mips support to Proxmox:
> 
> https://github.com/thenickdude/pve-qemu/tree/alien-architectures
> 
> It builds and installs to replace Proxmox's native pve-qemu package, but adds support for mips-softmmu, mips64-softmmu, mips64el-softmmu, mipsel-softmmu, ppc-softmmu, ppc64-softmmu, riscv32-softmmu, and riscv64-softmmu.
> 
> You can build it on Proxmox (or, better, a Debian 10 container with the Proxmox no-subscription repo added to apt.sources) like so:
> 
> ```shell
> apt-get build-dep qemu
> apt install libjemalloc-dev libpci-dev libproxmox-backup-qemu0-dev libsdl1.2-dev libsystemd-dev meson python3-sphinx quilt texi2html check lintian
> 
> git clone -b alien-architectures https://github.com/thenickdude/pve-qemu.git
> cd pve-qemu
> make
> ```
> 
> Install the resulting debs with "dpkg -i *.deb" and it'll add qemu-system-mips etc for you (as well as replacing your regular qemu-system-x86_64 binary).

That didin't quite work in a LXC Debian 10 container, with the proxmox no-subscription repo.

```
make[3]: Leaving directory '/root/pve-qemu/pve-qemu-kvm-5.2.0/build'
make[2]: Leaving directory '/root/pve-qemu/pve-qemu-kvm-5.2.0'
# remove Alpha files
rm /root/pve-qemu/pve-qemu-kvm-5.2.0/debian/pve-qemu-kvm/usr/share/kvm/palcode-clipper
# remove RISC-V files
rm /root/pve-qemu/pve-qemu-kvm-5.2.0/debian/pve-qemu-kvm/usr/share/kvm/opensbi-riscv32-generic-fw_dynamic.elf
rm /root/pve-qemu/pve-qemu-kvm-5.2.0/debian/pve-qemu-kvm/usr/share/kvm/opensbi-riscv64-generic-fw_dynamic.elf
# Remove things we don't package at all, would be a "kvm-dev" package
rm -Rf /root/pve-qemu/pve-qemu-kvm-5.2.0/debian/pve-qemu-kvm/usr/include/linux/
rm -Rf /root/pve-qemu/pve-qemu-kvm-5.2.0/debian/pve-qemu-kvm/usr/include
rm -f /root/pve-qemu/pve-qemu-kvm-5.2.0/debian/pve-qemu-kvm/usr/lib/kvm/qemu-bridge-helper
rm -f /root/pve-qemu/pve-qemu-kvm-5.2.0/debian/pve-qemu-kvm/usr/lib/kvm/virtfs-proxy-helper
# CPU flags are static for QEMU version, allows avoiding more costly checks
/root/pve-qemu/pve-qemu-kvm-5.2.0/debian/pve-qemu-kvm/usr/bin/qemu-system-x86_64 -cpu help | ./debian/parse-cpu-flags.pl > /root/pve-qemu/pve-qemu-kvm-5.2.0/debian/pve-qemu-kvm/usr/share/kvm/recognized-CPUID-flags-x86_64
/root/pve-qemu/pve-qemu-kvm-5.2.0/debian/pve-qemu-kvm/usr/bin/qemu-system-x86_64 -machine help | ./debian/parse-machines.pl > /root/pve-qemu/pve-qemu-kvm-5.2.0/debian/pve-qemu-kvm/usr/share/kvm/machine-versions-x86_64.json
Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./debian/parse-machines.pl line 6.
BEGIN failed--compilation aborted at ./debian/parse-machines.pl line 6.
make[1]: *** [debian/rules:129: install] Error 2
make[1]: Leaving directory '/root/pve-qemu/pve-qemu-kvm-5.2.0'
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make: *** [Makefile:36: pve-qemu-kvm_5.2.0-3_amd64.deb] Error 2
```

**Comment by thenickdude** [comment]
Ah I think you need libjson-perl too

**Comment by samip5** [comment]
Okey I got it installed but it does not ship/usr/lib/qemu/qemu-bridge-helper which is needed here: https://www.nicksherlock.com/2017/08/emulating-mips-guests-in-proxmox/.

**Comment by thenickdude** [comment]
You'll have to figure that one out, I haven't had cause to run them this way recently.
